language: swift
os: osx
osx_image: xcode12
xcode_project: DenCore.xcodeproj # path to your xcodeproj folder
xcode_scheme: DenCoreTests
xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11
